export enum ModelNames {
  ROLES = 'roles',
  ROLE_OPTIONS = 'roleoptions',
  ADMINS = 'admins',
  STUDENTS = 'students',
  INSTITUTES = 'institutes',
  PARTNERS = 'partners',
  USERS = 'users',
  COURSES = 'courses',
  COURSE_OPTIONS = 'courseoptions',
  DESIGNATIONS = 'designations',
  STAFFS = 'staffs',
  INSTITUTE_ROLES = 'institute_roles',
  INSTITUTE_ROLE_OPTIONS = 'institute_role_options',
  INSTITUTE_STAFFS = 'institute_staffs',
  PARTNER_ROLES = 'partner_roles',
  PARTNER_ROLE_OPTIONS = 'partner_role_options',
  PARTNER_STAFFS = 'partner_staffs',
}
